ktor:
  application:
    modules:
      - com.misaka.ApplicationKt.module
  deployment:
    port: 19327

database:
  driver: "org.postgresql.Driver"
  url: "jdbc:postgresql://db:5432/mydb"
  username: "postgres"
  password: "pass"
  maximumPoolSize: 10
  minimumIdle: 2
  maxLifetime: 1800000  # 30分钟
  idleTimeout: 600000   # 10分钟

redis:
  default:
    host: "redis"
    port: 6379
    password: ""
    timeout: 2000         # 毫秒
    db: 2
  task:
    host: "redis"
    port: 6379
    password: ""

jwt:
  domain: "http://localhost:19327/"
  audience: "ktor-audience"
  realm: "ktor local dev"
  secret: "local-secret-key"
  validityInMs: 600000   # 10分钟
